image:
  file: gitpod/.gitpod.dockerfile
ports:
  - port: 4000
    onOpen: open-preview 
tasks:
  - name: Phx
    init: gitpod/init.sh
    command: chmod +x gitpod/start.sh && gitpod/start.sh

vscode:
  extensions:
    - "jakebecker.elixir-ls"